import mongoose from "mongoose";

const testSchema = new mongoose.Schema({
  company_address: { type: String, required: false, default: "" },
  name: { type: String, required: false, default: "" },
  fin: { type: String, required: false, default: "" },
  dob: { type: String, required: false, default: "" },
  sex: { type: String, required: false, default: "" },
  empno: { type: String, required: false, default: "" },
  date: { type: String, required: false, default: "" },
  jobt: { type: String, required: false, default: "" },
  yrs_exposure: { type: String, required: false, default: "" },
  dept: { type: String, required: false, default: "" },
  ihd: { type: String, required: false, default: "" },
  excessive_noise: { type: String, required: false, default: "" },
  hearing_protectors: { type: String, required: false, default: "" },
  air_l0_25: { type: String, required: false, default: "" },
  air_l0_5: { type: String, required: false, default: "" },
  air_l1: { type: String, required: false, default: "" },
  air_l2: { type: String, required: false, default: "" },
  air_l3: { type: String, required: false, default: "" },
  air_l4: { type: String, required: false, default: "" },
  air_l6: { type: String, required: false, default: "" },
  air_l8: { type: String, required: false, default: "" },
  bone_l0_25: { type: String, required: false, default: "" },
  bone_l0_5: { type: String, required: false, default: "" },
  bone_l1: { type: String, required: false, default: "" },
  bone_l2: { type: String, required: false, default: "" },
  bone_l3: { type: String, required: false, default: "" },
  bone_l4: { type: String, required: false, default: "" },
  bone_l6: { type: String, required: false, default: "" },
  bone_l8: { type: String, required: false, default: "" },
  air_r0_25: { type: String, required: false, default: "" },
  air_r0_5: { type: String, required: false, default: "" },
  air_r1: { type: String, required: false, default: "" },
  air_r2: { type: String, required: false, default: "" },
  air_r3: { type: String, required: false, default: "" },
  air_r4: { type: String, required: false, default: "" },
  air_r6: { type: String, required: false, default: "" },
  air_r8: { type: String, required: false, default: "" },
  bone_r0_25: { type: String, required: false, default: "" },
  bone_r0_5: { type: String, required: false, default: "" },
  bone_r1: { type: String, required: false, default: "" },
  bone_r2: { type: String, required: false, default: "" },
  bone_r3: { type: String, required: false, default: "" },
  bone_r4: { type: String, required: false, default: "" },
  bone_r6: { type: String, required: false, default: "" },
  bone_r8: { type: String, required: false, default: "" },
  name_and_signature: { type: String, required: false, default: "" },
  date_tested: { type: String, required: false, default: "" },

  // Optional fields
  dwd_right: { type: String, required: false, default: "" },
  dwd_left: { type: String, required: false, default: "" },
  otoscopy_right: { type: String, required: false, default: "" },
  otoscopy_left: { type: String, required: false, default: "" },
  diagnosis: { type: String, required: false, default: "" },
  action_plans: { type: String, required: false, default: "" },
  action_plans_text: { type: String, required: false, default: "" },
  certification: { type: String, required: false, default: "" },

  // New fields
  statutory: { type: String, required: false, default: "" },
  notify: { type: String, required: false, default: "" },
  IHDinf: { type: String, required: false, default: "" },
  IHDiag: { type: String, required: false, default: "" },
  occ_hist: { type: String, required: false, default: "" },
  ear_discharge: { type: String, required: false, default: "" },
  ear_operation: { type: String, required: false, default: "" },
  ringing_ears: { type: String, required: false, default: "" },
  head_or_ear: { type: String, required: false, default: "" },
  ear_problem: { type: String, required: false, default: "" },
  loud_noise_exposure: { type: String, required: false, default: "" },
  medication: { type: String, required: false, default: "" },
  military_service: { type: String, required: false, default: "" },
  medical_problem: { type: String, required: false, default: "" },
  med_hist: { type: String, required: false, default: "" },
  other_info: { type: String, required: false, default: "" },
  counsel: { type: String, required: false, default: "" },
  protect: { type: String, required: false, default: "" },
  prototype: { type: String, required: false, default: "" },
  profreq: { type: String, required: false, default: "" },
  demo: { type: String, required: false, default: "" },
  cleanfreq: { type: String, required: false, default: "" },
  rearex: { type: String, required: false, default: "" },
  learex: { type: String, required: false, default: "" },
  tester: { type: String, required: false, default: "" },
  review1yr: { type: String, required: false, default: "" },
  review6mo: { type: String, required: false, default: "" },
  tonotify: { type: String, required: false, default: "" },
  notified: { type: String, required: false, default: "" },
});

const Test = mongoose.models.Test || mongoose.model("Test", testSchema);

export default Test;
